type: release
name: redis_deploy
version: 0.1
description: Redis Pub Sub
ion: 0.0.1
apps:
  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: process_dispatcher
    description: Process Dispatcher Service
    version: 0.1
    processapp: [process_dispatcher, ion.services.cei.process_dispatcher_service, ProcessDispatcherService]

  - name: identity_management
    version: 0.1
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]
    config:
      level: identity_management

  - name: policy_management
    version: 0.1
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]

  - name: org_management
    version: 0.1
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]
    config:
      level: org_management

  - name: exchange_management
    version: 0.1
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]
    config:
      level: exchange_management
  - name: pubsub_management
    version: 0.1
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]

  - name: ingestion_management
    version: 0.1
    processapp: [ingestion_management, ion.services.dm.ingestion.ingestion_management_service, IngestionManagementService]

  - name: transform_management
    version: 0.1
    processapp: [transform_management, ion.services.dm.transformation.transform_management_service, TransformManagementService]

  - name: dataset_management
    version: 0.1
    processapp: [dataset_management, ion.services.dm.inventory.dataset_management_service, DatasetManagementService]

  - name: data_retriever
    version: 0.1
    processapp: [data_retriever, ion.services.dm.inventory.data_retriever_service, DataRetrieverService]

  - name: index_management
    version: 0.1
    processapp: [index_management, ion.services.dm.inventory.index_management_service, IndexManagementService]

  - name: user_notification
    version: 0.1
    processapp: [user_notification, ion.services.dm.presentation.user_notification_service, UserNotificationService]

  - name: service_gateway
    version: 0.1
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]

#  - name: catalog_management
#    version: 0.1
#    processapp: [catalog_management, ion.services.dm.presentation.catalog_management_service, CatalogManagementService]

#  - name: discovery
#    version: 0.1
#    processapp: [discovery, ion.services.dm.presentation.discovery_service, DiscoveryService]

#  - name: preservation_management
#    version: 0.1
#    processapp: [preservation_management, ion.services.dm.preservation.preservation_management_service, PreservationManagementService]


  - name: redis_stream_launcher
    description: A process which perodically emits a message on a particular stream (routing key)
    version: 0.1
    processapp: [redis_stream_launcher, examples.redis_pub_sub.redis_stream_launcher, RedisStreamLauncher]

  - name: redis_publisher1
    description: A process which perodically stores on redis and emits the same message on a particular stream (routing key)
    version: 0.1
    processapp: [redis_publisher, examples.redis_pub_sub.redis_publisher, RedisPublisher]

  - name: redis_publisher2
    description: A process which perodically stores on redis and emits the same message on a particular stream (routing key)
    version: 0.1
    processapp: [redis_publisher, examples.redis_pub_sub.redis_publisher, RedisPublisher]

  - name: redis_publisher3
    description: A process which perodically stores on redis and emits the same message on a particular stream (routing key)
    version: 0.1
    processapp: [redis_publisher, examples.redis_pub_sub.redis_publisher, RedisPublisher]

  - name: redis_transform1
    description: A transform which listens to an exchange
    version: 0.1
    processapp: [redis_transform1, examples.redis_pub_sub.redis_transform, RedisTransform]

  - name: redis_transform2
    description: A transform which listens to an exchange
    version: 0.1
    processapp: [redis_transform2, examples.redis_pub_sub.redis_transform, RedisTransform]

  - name: redis_transform3
    description: A transform which listens to an exchange
    version: 0.1
    processapp: [redis_transform3, examples.redis_pub_sub.redis_transform, RedisTransform]
