# predicates.yml

# This is the authoritative definition of all permissible association predicates in the system

# WARNING: !!! Make sure the same predicate does NOT occur twice in the list below !!!

PredicateTypes:
#SA
  hasAttachment:
    domain: [Resource]
    range: [Attachment]
  hasAssignment:
    domain: [PlatformDevice, InstrumentDevice]
    range: [LogicalPlatform, LogicalInstrument]
  hasParent:
    domain: [DataProducer]
    range: [DataProducer]
  hasDataset:
    domain: [DataProducer, DataProduct]
    range: [Dataset]
  hasDataProducer:
    domain: [DataProcess, InstrumentDevice, ExternalDataset, DataProduct ]
    range: [DataProducer]
  hasDataProduct:
    domain: [LogicalInstrument]
    range: [DataProduct]
  hasInputDataProducer:
    domain: [DataProducer]
    range: [DataProducer]
  hasInputProduct:
    domain: [DataProcess]
    range: [DataProduct]
  hasInstance:
    domain: [PlatformAgent, InstrumentAgent, DataProcessDefinition, ExternalDataAgent]
    range: [PlatformAgentInstance, InstrumentAgentInstance, DataProcess, ExternalDataAgentInstance]
  hasInstrument:
    domain: [PlatformDevice, LogicalPlatform]
    range: [InstrumentDevice, LogicalInstrument]
  hasModel:
    domain: [PlatformDevice, InstrumentDevice, SensorDevice, InstrumentAgent, PlatformAgent, DataSource, ExternalDataAgent]
    range: [PlatformModel, InstrumentModel, SensorModel, ExternalDataSourceModel]
  hasOutputProduct:
    domain: [DataProcess, InstrumentDevice, ExternalDataset]
    range: [DataProduct]
  hasPlatform:
    domain: [MarineFacility, Site, LogicalPlatform]
    range: [PlatformDevice, LogicalPlatform]
  hasSensor:
    domain: [InstrumentDevice]
    range: [SensorDevice]
  hasSite:
    domain: [MarineFacility, Site]
    range: [Site]
# DM
  hasArchive:
    domain: [Datastore]
    range: [PersistentArchive]
  hasCatalog:
    domain: [View]
    range: [Catalog]
  hasDatastore:
    domain: [View, Index]
    range: [Datastore]
  hasIndex:
    domain: [Catalog]
    range: [Index]
  hasOutStream:
    domain: [Transform]
    range: [Stream]
  hasProcessDefinition:
    domain: [Transform]
    range: [ProcessDefinition]
  hasSubscription:
    domain: [Transform, ExchangePoint]
    range: [Subscription]
  hasStream:
    domain: [Replay, DataProcess, DataProduct, Dataset, ExchangePoint, Subscription]
    range: [Stream]
  hasTopology:
    domain: [Stream, Subscription]
    range: [TopicTopology]
  hasTopicTopology:
    domain: [ExchangePoint]
    range: [TopicTopology]
  hasTransform:
    domain: [DataProcess, IngestionConfiguration]
    range: [Transform]
  hasNotification:
    domain: [UserIdentity]
    range: [NotificationRequest]
  hasStreamDefinition:
    domain: [Stream]
    range: [StreamDefinition]
# COI
  affiliatedWith:
    domain: [Org]
    range: [Org]
  hasAgent:
    domain: [LogicalInstrument, LogicalPlatform]
    range: [InstrumentAgent, PlatformAgent]
  hasAgentDefinition:
    domain: [InstrumentModel, PlatformModel, LogicalInstrument, LogicalPlatform]
    range: [AgentDefinition]
  hasAgentInstance:
    domain: [TaskableResource, PlatformDevice, InstrumentDevice, ExternalDataset]
    range: [AgentInstance, PlatformAgentInstance,InstrumentAgentInstance, ExternalDataAgentInstance]
  hasAttachment:
    domain: [InstrumentDevice]
    range: [Attachment]
  hasCredentials:
    domain: [UserIdentity]
    range: [UserCredentials]
  hasExchangeBroker:
    domain: [ExchangeSpace]
    range: [ExchangeBroker]
  hasExchangeName:
    domain: [ExchangeSpace]
    range: [ExchangeName]
  hasExchangePoint:
    domain: [ExchangeSpace]
    range: [ExchangePoint]
  hasExchangeSpace:
    domain: [Org]
    range: [ExchangeSpace]
  hasInfo:
    domain: [UserIdentity]
    range: [UserInfo]
  hasLifecycle:
    domain: [ResourceType]
    range: [ResourceLifecycle]
  hasMembership:
    domain: [Org]
    range: [UserIdentity]
  hasOwner:
    domain: [Resource]
    range: [UserIdentity]
  hasPolicy:
    domain: [Resource]
    range: [Policy]
  hasResource:
    domain: [Org]
    range: [Resource]
  hasRole:
    domain: [Conversation,UserIdentity]
    range: [ConversationRole,UserRole]
  hasType:
    domain: [Conversation]
    range: [ServiceDefinition]
# CEI
  supportsExecutionEngine:
    domain: [ProcessDefinition]
    range: [ExecutionEngineDefinition]
# EOI
  hasProvider:
    domain: [DataSource]
    range: [ExternalDataProvider]
  hasSource:
    domain: [ExternalDataset]
    range: [DataSource]

# Examples
  hasAccount:
    domain: [BankCustomer]
    range: [BankAccount]
