type: release
name: Release2Configuration SA services
version: 0.1
description: Release 2 SA integration test configuration
ion: 0.0.1
apps:

#  - name: datastore
#    description: Data store service
#    version: 0.1
#    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]
#    config:
#        type: CouchDB
#        forceClean: true


# CEI services

  - name: process_dispatcher
    description: Process Dispatcher Service
    version: 0.1
    processapp: [process_dispatcher, ion.services.cei.process_dispatcher_service, ProcessDispatcherService]


# COI services

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: identity_management
    version: 0.1
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]

  - name: policy_management
    version: 0.1
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]

  - name: org_management
    version: 0.1
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]

  - name: service_gateway
    version: 0.1
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

        

# DM services

  - name: pubsub_management
    version: 0.1
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]

  - name: ingestion_management
    version: 0.1
    processapp: [ingestion_management, ion.services.dm.ingestion.ingestion_management_service, IngestionManagementService]

  - name: transform_management
    version: 0.1
    processapp: [transform_management, ion.services.dm.transformation.transform_management_service, TransformManagementService]

  - name: dataset_management
    version: 0.1
    processapp: [dataset_management, ion.services.dm.inventory.dataset_management_service, DatasetManagementService]

  - name: data_retriever
    version: 0.1
    processapp: [data_retriever, ion.services.dm.inventory.data_retriever_service, DataRetrieverService]

  - name: index_management
    version: 0.1
    processapp: [index_management, ion.services.dm.inventory.index_management_service, IndexManagementService]

  - name: user_notification
    version: 0.1
    processapp: [user_notification, ion.services.dm.presentation.user_notification_service, UserNotificationService]

  - name: last_update_cache_launcher
    version: 0.1
    processapp: [cache_launcher, ion.processes.data.cache_launcher, CacheLauncher ]
    config:
      process:
        number_of_workers: 4



# SA services

  - name: data_acquisition_management
    version: 0.1
    processapp: [data_acquisition_management, ion.services.sa.acquisition.data_acquisition_management_service, DataAcquisitionManagementService]

  - name: data_product_management
    version: 0.1
    processapp: [data_product_management, ion.services.sa.product.data_product_management_service, DataProductManagementService]

  - name: data_process_management
    version: 0.1
    processapp: [data_process_management, ion.services.sa.process.data_process_management_service, DataProcessManagementService]

  - name: instrument_management
    version: 0.1
    processapp: [instrument_management, ion.services.sa.instrument.instrument_management_service, InstrumentManagementService]

  - name: marine_facility_management
    version: 0.1
    processapp: [marine_facility_management, ion.services.sa.marine_facility.marine_facility_management_service, MarineFacilityManagementService]

    
